const API_FAILURE = 'api/ERROR'

const SET_USERS = 'user/SET'
const UPDATE_USER = 'user/UPDATE'
const DELETE_USER = 'user/DELETE'

const SET_SHOPS = 'shop/SET'
const UPDATE_SHOP = 'shop/UPDATE'
const DELETE_SHOP = 'shop/DELETE'

const SET_CATEGORIES = 'category/SET'
const UPDATE_CATEGORY = 'category/UPDATE'
const DELETE_CATEGORY = 'category/DELETE'

const SET_CHECKLISTS = 'checklist/SET'
const SET_CHECKLIST_RESULT = 'checklist/SET_CHECKLIST_RESULT'
const SET_USER_CHECKLIST = 'checklist/SET_USER_CHECKLIST'
const SET_CHECKLIST_RESULT_DETAILS = 'checklist/SET_CHECKLIST_RESULT_DETAILS'
const SET_CHECKLIST_RESULT_DETAILS_EXCEL = 'checklist/SET_CHECKLIST_RESULT_DETAILS_EXCEL'
const SET_USER_CHECKLIST_DETAILS = 'checklist/SET_USER_CHECKLIST_DETAILS'
const UPDATE_CHECKLIST = 'checklist/UPDATE'
const UPDATE_CHECKLIST_ITEM_ANSWER = 'checklist/UPDATE_CHECKLIST_ITEM_ANSWER'
const DELETE_CHECKLIST = 'checklist/DELETE'

const LOGIN_SUCCESS = 'auth/LOGIN_SUCCES'
const LOGOUT = 'auth/LOGOUT'

const SET_BOARDS = 'board/SET_BOARDS'
const SET_BOARD_USERS = 'board/SET_BOARD_USERS'
const SET_USER_BOARDS = 'board/SET_USER_BOARDS'
const SET_POSTS = 'board/SET_POSTS'
const SET_USER_POSTS = 'board/SET_USER_POSTS'
const UPDATE_BOARD = 'board/UPDATE_BOARD'
const UPDATE_USER_POST = 'board/UPDATE_USER_POST'
const DELETE_BOARD = 'board/DELETE_BOARD'
const DELETE_USER_POST = 'board/DELETE_USER_POST'
const SET_ALARMS = 'alarm/SET_ALARMS'
const UPDATE_ALARMS = 'alarm/UPDATE_ALARMS'

export {
  API_FAILURE,
  SET_USERS,
  UPDATE_USER,
  DELETE_USER,
  SET_SHOPS,
  UPDATE_SHOP,
  DELETE_SHOP,
  SET_CATEGORIES,
  UPDATE_CATEGORY,
  DELETE_CATEGORY,
  SET_CHECKLISTS,
  SET_USER_CHECKLIST,
  SET_CHECKLIST_RESULT,
  SET_CHECKLIST_RESULT_DETAILS,
  SET_CHECKLIST_RESULT_DETAILS_EXCEL,
  SET_USER_CHECKLIST_DETAILS,
  UPDATE_CHECKLIST,
  UPDATE_CHECKLIST_ITEM_ANSWER,
  DELETE_CHECKLIST,
  LOGIN_SUCCESS,
  LOGOUT,
  SET_BOARDS,
  SET_BOARD_USERS,
  SET_USER_BOARDS,
  SET_POSTS,
  SET_USER_POSTS,
  UPDATE_BOARD,
  UPDATE_USER_POST,
  DELETE_BOARD,
  DELETE_USER_POST,
  SET_ALARMS,
  UPDATE_ALARMS
}
