const API_FAILURE = 'api/ERROR'

const SET_USERS = 'user/SET'
const UPDATE_USER = 'user/UPDATE'
const DELETE_USER = 'user/DELETE'

const SET_SHOPS = 'shop/SET'
const UPDATE_SHOP = 'shop/UPDATE'
const DELETE_SHOP = 'shop/DELETE'

const SET_CATEGORIES = 'category/SET'
const UPDATE_CATEGORY = 'category/UPDATE'
const DELETE_CATEGORY = 'category/DELETE'

const SET_CHECKLISTS = 'checklist/SET'
const SET_USER_CHECKLIST = 'checklist/SET_USER_CHECKLIST'
const SET_USER_CHECKLIST_DETAILS = 'checklist/SET_USER_CHECKLIST_DETAILS'
const UPDATE_CHECKLIST = 'checklist/UPDATE'
const DELETE_CHECKLIST = 'checklist/DELETE'

const LOGIN_SUCCESS = 'auth/LOGIN_SUCCES'
const LOGOUT = 'auth/LOGOUT'

export {
  API_FAILURE,
  SET_USERS,
  UPDATE_USER,
  DELETE_USER,
  SET_SHOPS,
  UPDATE_SHOP,
  DELETE_SHOP,
  SET_CATEGORIES,
  UPDATE_CATEGORY,
  DELETE_CATEGORY,
  SET_CHECKLISTS,
  SET_USER_CHECKLIST,
  SET_USER_CHECKLIST_DETAILS,
  UPDATE_CHECKLIST,
  DELETE_CHECKLIST,
  LOGIN_SUCCESS,
  LOGOUT
}
